# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
'''
Your Code
'''
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

# 一個是全為零
# 一個是極度接近零的數

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件

'''
Your Code
'''

In [9]:
# 參考解答

a = np.random.rand(2, 3)
print(a)

'''
Your Code
'''
a = np.rint(a)
print(a)

[[0.74080426 0.62648654 0.63100044]
 [0.79776795 0.17056215 0.11278313]]
[[1. 1. 1.]
 [1. 0. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [17]:
import random
m = 20
n = 40

'''
Your Code
'''
a = np.random.randint(m, n,size = (2,3))
a

array([[28, 25, 30],
       [22, 27, 24]])